### ISSUE TITLE
append file error

### ISSUE THREAD

**Issue by ccx0lw** [awslabs/mountpoint-s3-csi-driver#103]
/kind bug

**What happened?**

`

bash-4.4$ cd /data/
bash-4.4$ ls
'Tue Dec 12 08:56:36 UTC 2023.txt'
bash-4.4$ ls
'Tue Dec 12 08:56:36 UTC 2023.txt'
bash-4.4$ echo 1 > 1.txt
bash-4.4$ cat 1.txt 
1
bash-4.4$ echo 11 >> 1.txt
bash: 1.txt: Operation not permitted
bash-4.4$ cat 1.txt
1
bash-4.4$ ls -l
total 1
-rw-r--r-- 1 1000 2000  2 Dec 12 08:57  1.txt
-rw-r--r-- 1 1000 2000 26 Dec 12 08:56 'Tue Dec 12 08:56:36 UTC 2023.txt'
`

**What you expected to happen?**

echo 11 >> 1.txt

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):   EKS 1.27
- Driver version:  v1.1.0-eksbuild.1

**Comment by equusit** [comment]
I think that this issue is potentially mentioned here https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#file-system-configuration. I can also replicate this issue - editing the same file with vi however works completely correctly

**Comment by dlakhaws** [comment]
Mountpoint currently doesn't allow you to append to files in that way and there is no plan in their public roadmap to do so. Take a look at [this documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#reading-and-writing-files) for more detail! If you'd like you can cut them a feature request. They are working on a feature to [overwrite files](https://github.com/awslabs/mountpoint-s3/pull/487) but that won't fix the append issue you are referencing here.

**Comment by ccx0lw** [comment]
thank you.
