### ISSUE TITLE
Make hostTokenPath configurable (/var/lib/kubelet/plugins/s3.csi.aws.com/token)

### ISSUE THREAD

**Issue by mikkeloscar** [awslabs/mountpoint-s3-csi-driver#106]
/kind bug

**What happened?**

The csi-driver is making assumptions about the kubelet directory (default `/var/lib/kubelet`) so it doesn't work in environments not running with the default. Specifically this constant: https://github.com/awslabs/mountpoint-s3-csi-driver/blob/d32aaa314e537900f2c5e66bac420e11a8b97e07/pkg/driver/mount.go#L46 means that in our environment where the kubelet directory is in a different location the `AWS_WEB_IDENTITY_TOKEN_FILE` doesn't work.

**What you expected to happen?**

It should be possible to define a custom path for the kubelet directory e.g. via a flag, such that `AWS_WEB_IDENTITY_TOKEN_FILE` can work in environments with custom settings. It's fine if the current constant is the default, it should just be possible to change.

**How to reproduce it (as minimally and precisely as possible)?**

Run kubelet with a different setting for `--root-dir` and configure the monthpath accordingly in the `s3-csi-driver` daemonset.

We run with a non-standard root because we do some tricks on the AMI to put the root on the root disk for instances without instance-store and for instance-storage instance-types, we put the root directory on the SSD (I don't think the actual use case is relevant, just to give context why we have it different from the default).

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by dlakhaws** [comment]
Thank you for the report. We are indeed hardcoding that path and need to make a fix for setups with non a standard `root-dir`. This will be planned for our next release.

**Comment by mikkeloscar** [comment]
Great! looking forward to that.

jFYI: even with this fixed I found another issue with mountpoint-s3: https://github.com/awslabs/mountpoint-s3/issues/675

**Comment by mikkeloscar** [comment]
> jFYI: even with this fixed I found another issue with mountpoint-s3: https://github.com/awslabs/mountpoint-s3/issues/675

This issue is fixed by setting `AWS_DEFAULT_REGION` on the daemonset suhc that mountpoint-s3 uses the right credentials chain, see description of the issue: https://github.com/awslabs/mountpoint-s3/issues/675#issuecomment-1869637085

**Comment by dlakhaws** [comment]
the kubelet dir is now configurable after the merge of the most recent [PR](https://github.com/awslabs/mountpoint-s3-csi-driver/pull/116), and will be available in v1.2 release which should be available later this month!

**Comment by mikkeloscar** [comment]
Thanks!

I have tested building from latest commit and this works! Looking forward to the official release.
