### ISSUE TITLE
Support customizing tolerations

### ISSUE THREAD

**Issue by andyndang** [awslabs/mountpoint-s3-csi-driver#109]
/feature

**Is your feature request related to a problem? Please describe.**
We have nodes with taints and the driver is not being scheduled there

**Describe the solution you'd like in detail**
Similiar to the eks-pod-identity-agent configuration that allows taints

**Comment by dlakhaws** [comment]
Thank you for the feature request. This is something we are tracking, we are planning to publish a public roadmap shortly and will provide updates on the timeline for adding this feature.

**Comment by dlakhaws** [comment]
[Custom tolerations](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md#configure-driver-toleration-settings) are now supported. This will be a part of the next driver release.

**Comment by yitsehong** [comment]
Where is the managed addons using value? I am encounter the problem by using taint. Other Managed CSI like EBS or EFS have tolerations for all node
```
      tolerations:
      - operator: Exists
```
Would you consider put the tolerations in default value?

**Comment by dlakhaws** [comment]
Yes, tolerations will be a default value (set to `False`) in our next release of the driver. We will notify in this thread when that's available for EKS Addon.

**Comment by jjkr** [comment]
Custom tolerations has been released in v1.4.0. It is currently available via helm install and will be rolling out as an eks addon next week.

**Comment by olsib** [comment]
This is not working with the EKS Addon:
```Error: error updating EKS Add-On (cluster-name:aws-mountpoint-s3-csi-driver): InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.tolerations: is not defined in the schema and the schema does not allow additional properties]
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "xxx"
│   },
│   AddonName: "aws-mountpoint-s3-csi-driver",
│   ClusterName: "cluster-name",
│   Message_: "ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.tolerations: is not defined in the schema and the schema does not allow additional properties]"
│ }
│ 
```
I tried v 1.4.0-eksbuild.1 & v 1.5.1-eksbuild.1

Can you please reopen ?

**Comment by barryib** [comment]
The daemonset should all taints by default. This is the case for [EFS CSI driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v2.0.5/charts/aws-efs-csi-driver/values.yaml#L160-L161), [EBS CSI driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v1.32.0/charts/aws-ebs-csi-driver/values.yaml#L368-L371) and mostly all critical daemonsets. I would suggest to even follow the same implementation than EFS and EBS CSI drivers.

In our case, we use Karpenter by exemple and taint/tolarations to separate workloads. EBS CSI drivers and EFS CSI drivers are working well. But getting toleration issues for S3 CSI driver.

Also related to:
- https://github.com/aws/containers-roadmap/issues/2363
- https://github.com/aws/containers-roadmap/issues/2220

**Comment by unexge** [comment]
v1.8.0 of our EKS add-on has been released with `node.tolerateAllTaints` and `node.tolerations` configuration values:
```bash
$ aws eks describe-addon-configuration --addon-name aws-mountpoint-s3-csi-driver --addon-version v1.8.0-eksbuild.1
{
    "addonName": "aws-mountpoint-s3-csi-driver",
    "addonVersion": "v1.8.0-eksbuild.1",
    "configurationSchema": "{\"$schema\":\"https://json-schema.org/draft/2019-09/schema\",\"additionalProperties\":false,\"description\":\"Configurable param
eters for Mountpoint for S3 CSI Driver\",\"properties\":{\"node\":{\"additionalProperties\":false,\"properties\":{\"tolerateAllTaints\":{\"default\":false,\"
description\":\"Mountpoint for S3 CSI Driver Pods will tolerate all taints and will be scheduled in all nodes\",\"type\":\"boolean\"},\"tolerations\":{\"defa
ult\":[],\"items\":{\"type\":\"object\"},\"title\":\"Tolerations for Mountpoint for S3 CSI Driver Pods\",\"type\":\"array\"}},\"type\":\"object\"}},\"type\":
\"object\"}",
    "podIdentityConfiguration": []
}
```

You can set `node.tolerateAllTaints` to `true` if you want CSI driver's Pods to schedule all nodes in the cluster, or you can configure `node.tolerations` array if you need more granularity.

For example:
```bash
$ aws eks create-addon --cluster-name ... \
    --addon-name aws-mountpoint-s3-csi-driver \
    --service-account-role-arn ... \
    --configuration-values '{"node":{"tolerateAllTaints":true}}' 
```

@barryib that's a good point, we discussed this and couldn't ensure if changing the default `tolerateAllTaints` to `true` from `false` would cause breaking something or CSI driver's Pods to be scheduled on some unexpected nodes. The risk is pretty low probably, but we wanted to go with exposing `node.tolerateAllTaints` for all installation options for now, and will rethink of making `node.tolerateAllTaints` `true` in the future releases.

Closing the issue now. Please let us know if you still experience the same problem with 1.8.0.
