### ISSUE TITLE
Can aws csi driver be installed on GKE cluster in GCP

### ISSUE THREAD

**Issue by iostreamdoth** [awslabs/mountpoint-s3-csi-driver#113]
Wondering if it is possible to use aws s3 csi driver on gke cluster. If so where can I find documentation around it ? It will be great if I can use Trusted web identity.

**Comment by jjkr** [comment]
The driver is not tested or officially supported with GKE, however I'm not aware of a reason it wouldn't work. You will have to use either [helm](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md#helm) or [kustomize](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md#kustomize) to install the driver and most likely k8s secrets will be the only option for configuring credentials.

**Comment by alexalex89** [comment]
Hint: Works when using ubuntu image instead of container optimized OS!
