### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by brodypiper** [awslabs/mountpoint-s3-csi-driver#117]
/kind bug
> **_NOTE:_**  If this is a filesystem related bug, please take a look at the [Mountpoint repo](https://github.com/awslabs/mountpoint-s3) to submit a [bug report](https://github.com/awslabs/mountpoint-s3/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml)

**What happened?**
An error occured while following the installation instructions here:
https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md#deploy-driver

When we try to install the driver via Helm, we get:
`$ helm upgrade --install aws-mountpoint-s3-csi-driver \
    --namespace kube-system \
    aws-mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver
Release "aws-mountpoint-s3-csi-driver" does not exist. Installing it now.
Error: Unable to continue with install: ServiceAccount "s3-csi-driver-sa" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "eksctl"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-mountpoint-s3-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"`

When trying to install via the kubectl method:
`$ kubectl apply -k "github.com/awslabs/mountpoint-s3-csi-driver/deploy/kubernetes/overlays/stable/"
Warning: resource serviceaccounts/s3-csi-driver-sa is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
serviceaccount/s3-csi-driver-sa configured
secret/aws-credentials-99tfgtg98h created
daemonset.apps/s3-csi-node created
csidriver.storage.k8s.io/s3.csi.aws.com created

$ kubectl get pods -n kube-system -l app.kubernetes.io/name=aws-mountpoint-s3-csi-driver
No resources found in kube-system namespace.
`

**What you expected to happen?**
I expected the instructions to yield a working implementation

**How to reproduce it (as minimally and precisely as possible)?**
Follow the install instructions in the docs here:
https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md#deploy-driver

**Anything else we need to know?**:
Helm chart seems broken; Kubectl does not create a deployment in kube-system (or any other namespace)

**Environment**
- Kubernetes version (use `kubectl version`): 
`Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.16-eks-8cb36c9
`
- Driver version: Latest available in Helm repository

**Comment by dlakhaws** [comment]
The issue seems to be related to the service account, not the install itself, were you able to install this once and now, when you're trying to re-install (after deleting the driver) it's facing an issue? Or is this your first time ever installing the driver?
You will likely have to delete old resources if they weren't cleaned up for a fresh install (helm takes care of it when you un-install, but if you delete via kustommize than the SA is not deleted, see the [warning at the end of the install page](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md#kustomize-1) for more details on this).

**Comment by dlakhaws** [comment]
Have you tried to uninstall the helm chart (`helm uninstall aws-mountpoint-s3-csi-driver --namespace kube-system`) instead of deleting the individual resources?

After you try the install command, can you run these commands and provide the output?

```
kubectl get events -n kube-system --sort-by=.metadata.creationTimestamp
kubectl logs -l app=s3-csi-node --namespace kube-system
```
