### ISSUE TITLE
providing credentials via awsAccessSecret does not work

### ISSUE THREAD

**Issue by Ognian** [awslabs/mountpoint-s3-csi-driver#133]
/kind bug

**What happened?**
Providing credentials via values.yaml awsAccessSecret does not work.
Creating /root/.aws/credentials with the correct credentials and retrying works.

**What you expected to happen?**
It should work without the credentials file on the host (/root/.aws/credentials)

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
 kubectl version  
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0+k3s1
- Driver version:
helm chart 1.2.0
Driver version: 1.2.0, Git commit: 8a832dc5e2fcaa01c02bece33c09517b5364687a, build date: 2024-01-17T16:52:48Z, nodeID: lp3dnode, mount-s3 version: 1.3.2

**Comment by jjkr** [comment]
Are you putting the actual credentials in `values.yaml`? Or are you trying to set a different name for the k8s secret?

The settings in `values.yaml` just tell the driver what key to use when looking for the actual key and key id. See the install doc for how to set the credentials with kubectl: https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/install.md#secret-object-setup. The example uses the default name of `aws-secret`.

If you are already setting the k8s secret according to the docs, please provide more details on how we can try to reproduce.

**Comment by Ognian** [comment]
Sorry, this was my fault. No everything works.
Thanks
Ognian
