### ISSUE TITLE
volume is not accessible from the container 

### ISSUE THREAD

**Issue by Ognian** [awslabs/mountpoint-s3-csi-driver#134]
/kind bug
**What happened?**
When successfully mounted, the s3 volume is not accessible from the container and shows permission denied:
<img width="661" alt="image" src="https://github.com/awslabs/mountpoint-s3-csi-driver/assets/1231174/8c986a4b-044e-4f67-b646-b05e76b179d1">
When accessing the mounted directory on the host (/var/lib/kubelet/pods/3e9a54c9-04b4-421b-a4e0-4d981e8c8139/volumes/kubernetes.io~csi/s3-pv/mount) everything is fine (we can read and write)....
Any ideas?

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use kubectl version):
kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0+k3s1
- Driver version:
helm chart 1.2.0
Driver version: 1.2.0, Git commit: https://github.com/awslabs/mountpoint-s3-csi-driver/commit/8a832dc5e2fcaa01c02bece33c09517b5364687a, build date: 2024-01-17T16:52:48Z, nodeID: lp3dnode, mount-s3 version: 1.3.2

**Comment by jjkr** [comment]
Is your container running as a non-root user? If so, you will need to add the `allow-other` mount option.

This issue for running as a non-root user has similar behavior and some more details: https://github.com/awslabs/mountpoint-s3-csi-driver/issues/118

**Comment by Ognian** [comment]
`--allow-other` is indeed the solution.
Thanks a lot
Ognian
