### ISSUE TITLE
Dynamic provisioning

### ISSUE THREAD

**Issue by RobKenis** [awslabs/mountpoint-s3-csi-driver#138]
/feature

**Is your feature request related to a problem? Please describe.**
For each PersistentVolumeClaim that I want backed by S3, I need to provision a PersistentVolume with a prefix.

**Describe the solution you'd like in detail**
I can create a PersistentVolumeClaim with a `s3-mountpoint` (?) storageClassName. Because of this, a PersistentVolume is created with the `prefix` MountOption.

**Describe alternatives you've considered**
For each helm chart we deploy with a PVC, we can include a PV as well. But this is not a clean solution, because as a service, I don't want to worry about the technology backing my storage. I just want to create a PVC and get it over with.

**Additional context**
We have a cluster with multiple tenants. Each tenant has a set of services that use PVCs. Deploying and maintaining a PV for all volumes is a lot overhead and dynamic provisioning would make my setup cleaner and my life easier.

**Comment by dlakhaws** [comment]
Thank you for the feature request. We're tracking a similar feature [here](https://github.com/awslabs/mountpoint-s3-csi-driver/issues/125) so we'll close this and track dynamic provisioning in the posted issue. Feel free to comment on that issue, +1 it, or open a new issue if it does not cover the use case mentioned here.
