### ISSUE TITLE
Mount 2 buckets to a pod

### ISSUE THREAD

**Issue by Guy-Royburt** [awslabs/mountpoint-s3-csi-driver#159]
When I mount 2 pvcs with 2 different bucket into a pod the pod is not starting and stuck on init state.

I expect that the pod will be start running

You can reproduce it by mounting 2 different pvcs with 2 different buckets into a pod

- Kubernetes version: 1.29

**Comment by aleochoam** [comment]
Just anyone else encountering this, make sure the handle is unique: 
https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/multiple_buckets_one_pod.yaml#L15C19-L15C56
