### ISSUE TITLE
v1.3.1 install-mountpoint failed with permission denied on Bottlerocket OS 1.19.2 (aws-k8s-1.29)

### ISSUE THREAD

**Issue by tanvp112** [awslabs/mountpoint-s3-csi-driver#160]
/kind bug
> **_NOTE:_**  If this is a filesystem related bug, please take a look at the [Mountpoint repo](https://github.com/awslabs/mountpoint-s3) to submit a [bug report](https://github.com/awslabs/mountpoint-s3/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml)

**What happened?**

s3-csi-dirver addon failed to install with latest (to this date) Bottlerocket 1.19.2-29cc92cc

**What you expected to happen?**

It was working with v1.2.0

**How to reproduce it (as minimally and precisely as possible)?**

Create a node group with Bottlerocket image and install the addon. The addon initContainer failed:

> Copying file mount-s3 
> Failed install binDir /mountpoint-s3/bin installDir /target: Failed to copy file mount-s3: open /target/mount-s3.tmp: permission denied
> 

https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/deploy/kubernetes/base/node-daemonset.yaml#L30

**Anything else we need to know?**:

https://github.com/awslabs/mountpoint-s3-csi-driver/pull/155

**Environment**
- Kubernetes version (use `kubectl version`): EKS 1.29
- Driver version: 1.3.1

**Comment by jjkr** [comment]
Bottlerocket support was added in CSI driver v1.4.0, which released yesterday to our helm charts. The eks add on will take several additional days to roll out and will be available sometime next week. You can find our officially supported OS matrix here: https://github.com/awslabs/mountpoint-s3-csi-driver#distros-support-matrix
