### ISSUE TITLE
No schedule on fargate node

### ISSUE THREAD

**Issue by vivien-ramahandry-fox** [awslabs/mountpoint-s3-csi-driver#176]
/feature

**Is your feature request related to a problem? Please describe.**
No schedule daemonset on fargate node

**Describe the solution you'd like in detail**
Add the possibility to use node affinity

Already created a [PR #175](https://github.com/awslabs/mountpoint-s3-csi-driver/pull/175) to solve the issue

```[tasklist]
### Tasks
```

**Comment by jjkr** [comment]
PR merged. Thanks!
