### ISSUE TITLE
Multiple AWS credentials

### ISSUE THREAD

**Issue by snowsky** [awslabs/mountpoint-s3-csi-driver#180]
I used one AWS credential for multiple S3 buckets, just a quick question for someone who may work around the issue that the helm chart allows to use different AWS S3 credentials for different buckets?

/triage support

**Comment by jjkr** [comment]
I am not aware of a workaround, but we have a feature request open here https://github.com/awslabs/mountpoint-s3-csi-driver/issues/136. Please give it a thumbs up if it is important to you. Closing this issue and will track the enhancement request under the other ticket.
