### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by Kamukage3e** [awslabs/mountpoint-s3-csi-driver#183]
/kind bug

**What happened?**
I have app that uses websocket connection and records session concurrently with writing session recordings to s3 bucket via mountpoint s3 csi driver.  when happening reconnect websocket connection it shows error " bad file descriptor cannot open the file" from s3 bucket.  My app will attempt open that file and update continuously  session recordings old created file even websocket reconnect.  video type is h.264
It worked only in yandex csi s3 driver
![image](https://github.com/awslabs/mountpoint-s3-csi-driver/assets/141987684/a2bdbc1f-ab90-46a0-bafa-dc843e3691a1)

**What you expected to happen?**
Need to add continuously old created file.  
**How to reproduce it (as minimally and precisely as possible)?**
I will help by my side to reproduce it on my own server 
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: v1.28.5-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-b9c9ed7
- Driver version: 
public.ecr.aws/mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver:v1.5.1

**Comment by arsh** [comment]
Hello @Kamukage3e.

Is you application attempting to append to an existing file? If yes, that is not supported by Mountpoint. For reference, here is a link to the writing semantics supported by Mountpoint[1].

If you need further help, can you provide the Mountpoint logs? To get the logs, below are some instructions.

```
# first find uid for a particular customer pod
$ CUSTOMER_POD_NAME=s3-app
$ kubectl get pods ${CUSTOMER_POD_NAME} -o jsonpath='{.metadata.uid}'
2208b8c6-0ff0-452b-9141-63173d54e3ee

# next, ssh into the node running the pod and execute the following to find systemd service name:
# NOTE: this won't work if service is already dead
$ CUSTOMER_POD_UID=2208b8c6-0ff0-452b-9141-63173d54e3ee
$ PV_NAME=s3-pv
$ ps -ef | grep "$CUSTOMER_POD_UID.*$PV_NAME" | grep -v "grep"
root      231632       1  0 12:57 ?        00:00:00 /opt/mountpoint-s3-csi/bin/mount-s3 s3-csi-driver /var/lib/kubelet/pods/24d1fdd3-1b53-45e9-a879-bb9a2cb29bfc/volumes/kubernetes.io~csi/s3-pv/mount --allow-delete --debug --debug-crt --log-metrics --region=eu-west-1 --user-agent-prefix=s3-csi-driver/1.0.0
$ MOUNT_PID=231632
$ UNIT=$(systemctl status $MOUNT_PID | grep --only-matching "mount-s3-.*\.service" | tail -1)

# finally fetch logs from the node
$ journalctl --unit $UNIT
```

[1] https://github.com/awslabs/mountpoint-s3-csi-driver/issues/182
