### ISSUE TITLE
Is there a way to add different aws account s3 bucket to mount in single Kubernetes cluster.

### ISSUE THREAD

**Issue by sudeepnandiqwe** [awslabs/mountpoint-s3-csi-driver#197]
/triage support
Is there a way to add different aws account s3 bucket to mount in single Kubernetes cluster
E.g. Aws account 1 - s3 bucket 1
      Aws account 2 - s3 bucket 1
      Aws account 3 - s3 bucket 1
using these CSI driver can we create PV's based on the account and bucket.

**Comment by passaro** [comment]
Hi @sudeepnandiqwe, have you looked into bucket policies (https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-policies.html)? You should be able to configure your buckets to grant cross-account access.
If that does not cover your use case, it would be great to hear more about it.

**Comment by manikandan-harman** [comment]
@passaro we are going to have multi-tenant s3 bucket sync. We will not be able to use the cross-account access in this case. is there any way to use different aws account with buckets as @sudeepnandiqwe mentioned?

**Comment by unexge** [comment]
Mountpoint CSI Driver [v1.9.0](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/CHANGELOG.md#v190) added support for Pod-level identity. Using this feature you can configure cross-account S3 Bucket access at Pod granularity. We documented cross-account access using both bucket policies and IRSA. See [Cross-account bucket access](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/docs/CONFIGURATION.md#cross-account-bucket-access) for more details. 

Closing this issue, please let us know if your use-case isn't covered with the mentioned approaches.
