### ISSUE TITLE
Is it possible to connect multiple PV/PVC to the same bucket prefix?

### ISSUE THREAD

**Issue by schlichtanders** [awslabs/mountpoint-s3-csi-driver#244]
Hi there, as kubernetes only allows sharing of PV/PVCs within the same namespace, but we would like to access the same storage from different namespaces, I was wondering whether mountpoint-s3-csi-driver supports this.

Concretely to have several PV/PVC combinations for different namespaces which still access the same s3 data. I couldn't find anything in the documentation.

/triage support

**Comment by muddyfish** [comment]
You're correct - currently it's not possible to use a single PVC across multiple namespaces, or a single PV in multiple PVCs.

If you configure the same S3 bucket and path in multiple volumes, you will have the same view of the data. I understand this is not ideal however. I'd recommend adding a 👍 to this feature request: https://github.com/awslabs/mountpoint-s3-csi-driver/issues/125

**Comment by schlichtanders** [comment]
it is a limitation of kubernetes, so yeah, nothing to do for mountpoint-s3
